In [2]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix

In [4]:
df = pd.read_csv('train.csv')

In [6]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
df.shape

(889, 12)

In [12]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [17]:
df1 = df.drop(['Cabin', 'PassengerId', 'Name', 'Ticket'],axis=1)

In [19]:
df1.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [21]:
df1.shape

(889, 8)

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  889 non-null    int64  
 1   Pclass    889 non-null    int64  
 2   Sex       889 non-null    object 
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64  
 5   Parch     889 non-null    int64  
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.7+ KB


In [26]:
df1.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [28]:
le = LabelEncoder()

In [30]:
df1['Sex'] = le.fit_transform(df1['Sex'])
df1['Embarked']=le.fit_transform(df1['Embarked'])

In [36]:
df1.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [40]:
y = df1['Survived']
X = df1.drop(['Survived'],axis=1)

In [41]:
y.count()

889

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.24,random_state=0)

In [45]:
clf=BernoulliNB()

In [47]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [49]:
accuracy_score(y_test,y_pred,normalize=True)

0.7523364485981309

In [51]:
confusion_matrix(y_test,y_pred)

array([[105,  23],
       [ 30,  56]], dtype=int64)

In [55]:
def Nav_Model(col):
    x = df1.drop([col], axis=1)
    y = df1[col]
    train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state = 0)
    model = BernoulliNB()
    model.fit(train_X, train_y)
    ypred = model.predict(test_X)
    print("==================================================================")
    print(f"Accuracy score is {accuracy_score(test_y, ypred)}")
    print("==================================================================")
    print(f"Confusion Matrix: \n{confusion_matrix(test_y, ypred)}")
    print("==================================================================")

In [57]:
Nav_Model('Pclass')

Accuracy score is 0.5767790262172284
Confusion Matrix: 
[[ 18   2  50]
 [  0   1  48]
 [ 10   3 135]]


In [59]:
Nav_Model('SibSp')

Accuracy score is 0.9250936329588015
Confusion Matrix: 
[[182   0   0   0   0   0   0]
 [  0  65   0   0   0   0   0]
 [  0   8   0   0   0   0   0]
 [  0   7   0   0   0   0   0]
 [  0   2   0   0   0   0   0]
 [  0   1   0   0   0   0   0]
 [  0   2   0   0   0   0   0]]


In [61]:
Nav_Model('Sex')

Accuracy score is 1.0
Confusion Matrix: 
[[ 98   0]
 [  0 169]]


In [64]:
Nav_Model('Parch')

Accuracy score is 0.8876404494382022
Confusion Matrix: 
[[198   0   0   0   0]
 [  0  33   7   0   0]
 [  0  21   6   0   0]
 [  0   1   0   0   0]
 [  0   0   1   0   0]]


In [67]:
Nav_Model('Embarked')

Accuracy score is 0.9176029962546817
Confusion Matrix: 
[[ 49   0   0]
 [  0   0  22]
 [  0   0 196]]
