# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.96911667 0.32931719 0.74807666]
  [0.17540277 0.16598262 0.09352122]
  [0.14613236 0.78939129 0.31006442]]

 [[0.00627115 0.93875322 0.37964233]
  [0.36800887 0.49651451 0.13667379]
  [0.1956028  0.77923814 0.63998251]]

 [[0.49276533 0.09179174 0.3010148 ]
  [0.67301194 0.63179147 0.02726886]
  [0.55791414 0.85583749 0.67988636]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
x = np.diag([1,2,3,4,4])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [6]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.89905398 0.82462236 0.48725342 0.85903784 0.79667886]
 [0.36596299 0.66258877 0.14497375 0.23042623 0.12633008]
 [0.11145001 0.05936627 0.11781299 0.65915073 0.64797933]
 [0.42889439 0.17219844 0.17817872 0.35842056 0.70517871]
 [0.34086251 0.61385987 0.07557189 0.47695509 0.07727536]]
After normalization:
[[1.         0.91135797 0.50957891 0.95234403 0.87807954]
 [0.36513184 0.7183891  0.10195157 0.20371855 0.07974847]
 [0.06202751 0.         0.06960531 0.71429467 0.70099044]
 [0.44007804 0.13437397 0.141496   0.35614942 0.76911027]
 [0.3352392  0.66035693 0.01929958 0.49731443 0.02132827]]


# 5.  How to find common values between two arrays?

In [9]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
a = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's date is: ",a)
b = np.datetime64('today', 'D')
print("Today's date is: ",b)
c = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's date is: ",c)

Yestraday's date is:  2020-07-27
Today's date is:  2020-07-28
Tomorrow's date is:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [16]:
x = np.random.randint(1,2,6)
print("First array:")
print(x)
y = np.random.randint(2,4,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not:")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 1 1 1]
Second array:
[2 3 3 3 2 3]
Test above two arrays are equal or not:
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [17]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.5573673  0.26023807 0.32988159 0.15849253 0.89400811 0.78034788
 0.75368929 0.48744307 0.05456453 0.20511581]
Maximum value replaced by 0:
[0.5573673  0.26023807 0.32988159 0.15849253 0.         0.78034788
 0.75368929 0.48744307 0.05456453 0.20511581]


# 9. How to print all the values of an array?

In [19]:
x = np.zeros((4, 4))
print(x)
# Just print the defined variable of array 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [20]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.29103899 0.86882128 0.71250613 0.94970122 0.42732235 0.31460848
  0.34520901 0.25186409 0.97659364 0.72556714]
 [0.95569805 0.63595718 0.10281709 0.70908668 0.70855654 0.16323335
  0.10212331 0.02056977 0.63600206 0.95497567]
 [0.51526335 0.71120365 0.14980291 0.11361311 0.81085084 0.60754197
  0.58673627 0.16453974 0.24155952 0.7087192 ]
 [0.44163798 0.18670248 0.61931016 0.80472982 0.77163511 0.55181722
  0.37039935 0.88275935 0.59439535 0.90055768]
 [0.93822455 0.93330319 0.04735598 0.0494873  0.07345233 0.74961513
  0.95295685 0.32943831 0.95453331 0.12656716]]

Subtract the mean of each row of the said matrix:

[[-0.29528425  0.28249805  0.1261829   0.36337799 -0.15900088 -0.27171475
  -0.24111422 -0.33445914  0.39027041  0.1392439 ]
 [ 0.45679608  0.13705521 -0.39608488  0.21018471  0.20965457 -0.33566862
  -0.39677866 -0.4783322   0.13710009  0.4560737 ]
 [ 0.05428029  0.2502206  -0.31118014 -0.34736995  0.34986778  0.14655891
   0.12575322 -0.29644332 -0.2

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [3]:
import numpy as np
a = np.ones(13)
print("The first vector is: ", a)
b = np.random.randint(0,len(a),20)
print("The second vector is: ",b)
a += np.bincount(b, minlength=len(a))
print("Thi final vector is: ",a)

The first vector is:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The second vector is:  [ 1 12  4  5 12  1  3  1  3  7  0  5  6  4 11  0  4  8  3  1]
Thi final vector is:  [3. 5. 1. 4. 4. 3. 2. 2. 2. 1. 1. 2. 3.]


# 12.How to get the diagonal of a dot product?

In [6]:
a = np.random.randint(0,10,(7,7))
print(a)

b = np.random.randint(0,10,(7,7))
print(b)

c = np.diag(np.dot(a, b))
print(c)

[[8 4 2 3 6 1 9]
 [0 0 2 6 1 4 6]
 [1 8 7 6 4 5 4]
 [3 7 1 1 5 6 2]
 [0 6 9 3 9 4 6]
 [6 4 1 6 7 8 8]
 [6 9 9 7 3 4 3]]
[[2 2 6 9 6 9 2]
 [2 0 6 4 0 4 0]
 [8 1 0 1 1 5 2]
 [0 7 0 5 1 3 2]
 [5 1 5 1 1 7 9]
 [7 5 2 1 2 8 3]
 [8 1 2 8 6 9 9]]
[149  71  92  88  65 278 110]


# 13.How to find the most frequent value in an array?

In [21]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 2 6 5 7 4 1 8 9 7 2 2 7 7 8 8 9 6 6 5 2 4 1 1 5 2 9 6 4 4 1 9 9 1 4 2 0
 5 7 8]
Most frequent value in the above array:
2


# 14.How to get the n largest values of an array

In [23]:
x = np.arange(24)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[23]


# 15.How to create a record array from a regular array?

In [8]:
a = np.array(['Ivar','Ragnar','Lagertha','Odin'])
b = np.array(['Liverpool','Atlanta','Milan','Arsenal'])
c = np.array(['Dark','Black Mirror','Bodyguard','Vikings'])
d = np.core.records.fromarrays([a, b, c])
print(d[0])
print(d[1])
print(d[2])
print(d[3])

('Ivar', 'Liverpool', 'Dark')
('Ragnar', 'Atlanta', 'Black Mirror')
('Lagertha', 'Milan', 'Bodyguard')
('Odin', 'Arsenal', 'Vikings')
